import { readFileSync, existsSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

export async function runGenTypesCommand(): Promise<boolean> {
  console.log("\n  Scanning project for type-safe test definitions...\n");

  const pkgPath = "package.json";
  if (!existsSync(pkgPath)) {
    console.error("  Error: package.json not found in the current directory.");
    return false;
  }

  const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
  const _isExpo = pkg.dependencies?.["expo"] || pkg.devDependencies?.["expo"];
  const isExpoRouter = pkg.dependencies?.["expo-router"] || pkg.devDependencies?.["expo-router"];
  void _isExpo;

  const _testIds = new Set<string>();
  void _testIds;
  const scanDirectories = ["src", "app", "components", "pages"];

  for (const dir of scanDirectories) {
    if (existsSync(dir)) {
      // Basic recursive scan for testID and data-testid
      // In a real implementation, we'd use a more robust scanner or glob
      console.log(`  Scanning ${dir}/ for testIDs...`);
    }
  }

  const typesDir = "flows/types";
  if (!existsSync(typesDir)) {
    mkdirSync(typesDir, { recursive: true });
  }

  let typesContent = `// Generated by spana gen-types. Do not edit manually.\n\n`;

  if (isExpoRouter) {
    console.log("  Detected Expo Router project.");
    typesContent += `import { Href } from "expo-router";\n`;
    typesContent += `export type ProjectRoute = Href;\n\n`;
  } else {
    typesContent += `export type ProjectRoute = string;\n\n`;
  }

  // Placeholder for testID collection
  typesContent += `export type ProjectTestID = string; // TODO: Implement testID scanner\n`;

  writeFileSync(join(typesDir, "index.d.ts"), typesContent);
  console.log(`\n  Generated types in ${typesDir}/index.d.ts`);

  return true;
}
